Drop support for i386 architecture
Removes package lists for i386, removes ifclass/hasclass checks for i386.
Removes "i386" to option `-a`.

UEFI 32bit boot on an AMD64 ISO should continue to work.

Link: https://github.com/grml/grml-live/issues/559

diff --git a/config/media-scripts/GRMLBASE/31-grub b/config/media-scripts/GRMLBASE/31-grub
--- a/config/media-scripts/GRMLBASE/31-grub
+++ b/config/media-scripts/GRMLBASE/31-grub
@@ -28,6 +28,7 @@ if ifclass ARM64 ; then
 fi
 
 if ifclass AMD64 ; then
+  # UEFI 64bit boot
   if [ -r "${target}"/usr/lib/grub/x86_64-efi/moddep.lst ] ; then
     GRUB_ARCHS+=(x86_64-efi)
     ADDITIONAL_MODULES[x86_64-efi]="efi_gop"
@@ -35,10 +36,8 @@ if ifclass AMD64 ; then
     echo "/usr/lib/grub/x86_64-efi/moddep.lst could not be found, skipping."
     echo "NOTE: grub-efi-amd64-bin not installed?"
   fi
-fi
 
-# note: enabled also on AMD64 for UEFI 32bit boot support
-if ifclass I386 || ifclass AMD64 ; then
+  # UEFI 32bit boot
   if [ -r "${target}"/usr/lib/grub/i386-efi/moddep.lst ] ; then
     GRUB_ARCHS+=(i386-efi)
     ADDITIONAL_MODULES[i386-efi]="efi_gop"
@@ -102,7 +101,7 @@ if [ "${ARCH}" = "arm64" ] ; then
   mkdir -p "${media_dir}"/boot/grub/arm64-efi/
   cp -a "${target}"/usr/lib/grub/arm64-efi/*.mod "${media_dir}"/boot/grub/arm64-efi/
   cp -a "${target}"/usr/lib/grub/arm64-efi/*.lst "${media_dir}"/boot/grub/arm64-efi/
-elif [ "${ARCH}" = "amd64" ] || [ "${ARCH}" = "i386" ] ; then
+elif [ "${ARCH}" = "amd64" ] ; then
   # grub-pc-bin
   mkdir -p "${media_dir}"/boot/grub/i386-pc/
   cp -a "${target}"/usr/lib/grub/*-pc/*.mod  "${media_dir}"/boot/grub/i386-pc/
@@ -136,64 +135,60 @@ for param in ARCH DATE DISTRI_INFO DISTRI_NAME GRML_NAME SQUASHFS_NAME \
 done
 
 
-# don't include shim + grubnetx64 + grub files in i386 netboot packages,
-# as those don't make much sense there
-if ifclass AMD64 || ifclass ARM64 ; then
-  if ! [ -r "${media_dir}/boot/grub/netboot.cfg" ] ; then
-    echo "W: File /boot/grub/netboot.cfg not found." >&2
-    echo "W: Are you using custom media-files which do not provide netboot.cfg?" >&2
-  else
-    cp --preserve=timestamp "${media_dir}/boot/grub/netboot.cfg" "${tftpboot_dir}/grub.cfg"
+if ! [ -r "${media_dir}/boot/grub/netboot.cfg" ] ; then
+  echo "W: File /boot/grub/netboot.cfg not found." >&2
+  echo "W: Are you using custom media-files which do not provide netboot.cfg?" >&2
+else
+  cp --preserve=timestamp "${media_dir}/boot/grub/netboot.cfg" "${tftpboot_dir}/grub.cfg"
 
-    if [ "$ARCH" = "amd64" ] ; then
-      if ! grml-live-copy-file-logged "${tftpboot_dir}"/shim.efi "${target}" \
-        /usr/lib/shim/shimx64.efi.signed \
-        /usr/lib/shim/shimx64.efi
-      then
-        echo "W: No shimx64.efi for usage with PXE boot found (shim-signed not present?)" >&2
-      fi
-
-      if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubx64.efi "${target}" \
-        /usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed \
-        /usr/lib/grub/x86_64-efi/monolithic/grubnetx64.efi
-      then
-        echo "W: No grubnetx64.efi for usage with PXE boot found (grub-efi-amd64-signed not present?)." >&2
-      fi
-
-      # UEFI 32bit boot
-      if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubia32.efi "${target}" \
-        /usr/lib/grub/i386-efi-signed/grubnetia32.efi.signed \
-        /usr/lib/grub/i386-efi/monolithic/grubnetia32.efi
-      then
-        echo "W: No grubnetia32.efi for usage with PXE boot found (grub-efi-ia32-unsigned present?)." >&2
-      fi
+  if [ "$ARCH" = "amd64" ] ; then
+    if ! grml-live-copy-file-logged "${tftpboot_dir}"/shim.efi "${target}" \
+      /usr/lib/shim/shimx64.efi.signed \
+      /usr/lib/shim/shimx64.efi
+    then
+      echo "W: No shimx64.efi for usage with PXE boot found (shim-signed not present?)" >&2
     fi
 
-    if [ "$ARCH" = "arm64" ] ; then
-      if ! grml-live-copy-file-logged "${tftpboot_dir}"/shim.efi "${target}" \
-        /usr/lib/shim/shimaa64.efi.signed \
-        /usr/lib/shim/shimaa64.efi
-      then
-        echo "W: No shimaa64.efi for usage with PXE boot found (shim-signed not present?)" >&2
-      fi
-
-      if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubaa64.efi "${target}" \
-        /usr/lib/grub/arm64-efi-signed/grubnetaa64.efi.signed \
-        /usr/lib/grub/arm64-efi/monolithic/grubnetaa64.efi
-      then
-        echo "W: No grubnetaa64.efi for usage with PXE boot found (grub-efi-arm64-signed not present?)." >&2
-      fi
+    if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubx64.efi "${target}" \
+      /usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed \
+      /usr/lib/grub/x86_64-efi/monolithic/grubnetx64.efi
+    then
+      echo "W: No grubnetx64.efi for usage with PXE boot found (grub-efi-amd64-signed not present?)." >&2
     fi
 
-    if [ -r "${target}"/usr/share/grub/unicode.pf2 ] ; then
-      echo "I: Installing ${target}/usr/share/grub/unicode.pf2 as grub/fonts/unicode.pf2 in netboot package"
-      mkdir -p "${tftpboot_dir}"/grub/fonts/
-      cp --preserve=timestamp "${target}"/usr/share/grub/unicode.pf2 "${tftpboot_dir}"/grub/fonts/
-    else
-      echo "W: No unicode.pf2 for usage with PXE boot found (grub-common not present?)" >&2
+    # UEFI 32bit boot
+    if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubia32.efi "${target}" \
+      /usr/lib/grub/i386-efi-signed/grubnetia32.efi.signed \
+      /usr/lib/grub/i386-efi/monolithic/grubnetia32.efi
+    then
+      echo "W: No grubnetia32.efi for usage with PXE boot found (grub-efi-ia32-unsigned present?)." >&2
     fi
   fi
-fi # amd64 or arm64
+
+  if [ "$ARCH" = "arm64" ] ; then
+    if ! grml-live-copy-file-logged "${tftpboot_dir}"/shim.efi "${target}" \
+      /usr/lib/shim/shimaa64.efi.signed \
+      /usr/lib/shim/shimaa64.efi
+    then
+      echo "W: No shimaa64.efi for usage with PXE boot found (shim-signed not present?)" >&2
+    fi
+
+    if ! grml-live-copy-file-logged "${tftpboot_dir}"/grubaa64.efi "${target}" \
+      /usr/lib/grub/arm64-efi-signed/grubnetaa64.efi.signed \
+      /usr/lib/grub/arm64-efi/monolithic/grubnetaa64.efi
+    then
+      echo "W: No grubnetaa64.efi for usage with PXE boot found (grub-efi-arm64-signed not present?)." >&2
+    fi
+  fi
+
+  if [ -r "${target}"/usr/share/grub/unicode.pf2 ] ; then
+    echo "I: Installing ${target}/usr/share/grub/unicode.pf2 as grub/fonts/unicode.pf2 in netboot package"
+    mkdir -p "${tftpboot_dir}"/grub/fonts/
+    cp --preserve=timestamp "${target}"/usr/share/grub/unicode.pf2 "${tftpboot_dir}"/grub/fonts/
+  else
+    echo "W: No unicode.pf2 for usage with PXE boot found (grub-common not present?)" >&2
+  fi
+fi
 
 if ifclass AMD64 ; then
   echo "I: Copying GRUB i386-pc modules to ISO"
